import jsPDF from 'jspdf';
import { ParentBrief } from '../types';

export class PDFService {
  static generateParentBrief(brief: ParentBrief): void {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const margin = 20;
    let yPosition = 30;
    
    // Header
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('Astral - Career Plan Summary', margin, yPosition);
    doc.text('पाथसाथी - करियर योजना सारांश', margin, yPosition + 10);
    
    yPosition += 30;
    
    // Student Info
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Student Information / छात्र जानकारी', margin, yPosition);
    
    yPosition += 15;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(`Name / नाम: ${brief.studentName}`, margin, yPosition);
    
    yPosition += 10;
    doc.text(`Chosen Career Path / चुना गया करियर पथ: ${brief.chosenPath.title}`, margin, yPosition);
    doc.text(`${brief.chosenPath.titleHindi}`, margin, yPosition + 8);
    
    yPosition += 25;
    
    // Career Details
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Career Path Details / करियर पथ विवरण', margin, yPosition);
    
    yPosition += 15;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    
    const description = doc.splitTextToSize(brief.chosenPath.description, pageWidth - 2 * margin);
    doc.text(description, margin, yPosition);
    yPosition += description.length * 6 + 10;
    
    // Timeline
    doc.setFont('helvetica', 'bold');
    doc.text('Timeline / समयसीमा:', margin, yPosition);
    doc.setFont('helvetica', 'normal');
    doc.text(brief.timeline, margin + 50, yPosition);
    
    yPosition += 15;
    
    // Salary Range
    doc.setFont('helvetica', 'bold');
    doc.text('Expected Salary Range / अपेक्षित वेतन सीमा:', margin, yPosition);
    doc.setFont('helvetica', 'normal');
    doc.text(`₹${brief.chosenPath.salaryRange.entry.toLocaleString()} - ₹${brief.chosenPath.salaryRange.experienced.toLocaleString()}`, margin, yPosition + 8);
    
    yPosition += 25;
    
    // Budget Breakdown
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Budget Breakdown / बजट विवरण', margin, yPosition);
    
    yPosition += 15;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(`Course Fees / कोर्स फीस: ₹${brief.budgetBreakdown.courses.toLocaleString()}`, margin, yPosition);
    yPosition += 8;
    doc.text(`Materials & Resources / सामग्री और संसाधन: ₹${brief.budgetBreakdown.materials.toLocaleString()}`, margin, yPosition);
    yPosition += 8;
    doc.setFont('helvetica', 'bold');
    doc.text(`Total Investment / कुल निवेश: ₹${brief.budgetBreakdown.total.toLocaleString()}`, margin, yPosition);
    
    yPosition += 25;
    
    // Support Tips
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('How You Can Help / आप कैसे मदद कर सकते हैं', margin, yPosition);
    
    yPosition += 15;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    
    brief.supportTips.forEach((tip, index) => {
      const wrappedTip = doc.splitTextToSize(`${index + 1}. ${tip}`, pageWidth - 2 * margin - 10);
      doc.text(wrappedTip, margin + 5, yPosition);
      yPosition += wrappedTip.length * 6 + 5;
    });
    
    yPosition += 15;
    
    // Expected Outcomes
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Expected Outcomes / अपेक्षित परिणाम', margin, yPosition);
    
    yPosition += 15;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    
    brief.expectedOutcomes.forEach((outcome, index) => {
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 30;
      }
      const wrappedOutcome = doc.splitTextToSize(`${index + 1}. ${outcome}`, pageWidth - 2 * margin - 10);
      doc.text(wrappedOutcome, margin + 5, yPosition);
      yPosition += wrappedOutcome.length * 6 + 5;
    });
    
    // Footer
    yPosition += 20;
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 30;
    }
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'italic');
    doc.text('Generated by Astral - AI Career Co-pilot', margin, yPosition);
    doc.text('For support: contact@Astral.in | 1800-XXX-XXXX', margin, yPosition + 8);
    
    // Save the PDF
    doc.save(`${brief.studentName}_Career_Plan.pdf`);
  }
}